[package]
name = "input_test"
version = "0.1.0"
authors = ["Isaac Marovitz <42140194+IsaacMarovitz@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"